name: Docker

# This workflow can be triggered by two events: a published release or a 
# manual dispatch. When triggered by a release, it pushes a Docker image 
#tagged with both 'latest' and the release version. If triggered manually, 
# the Docker image is tagged with the branch name (e.g., main, dev etc).
on:
  release:
    types: [published]
  workflow_dispatch:


# --------------------------------------------------------------
# Variables
# --------------------------------------------------------------
env:
  PLATFORMS: linux/amd64,linux/arm64


# --------------------------------------------------------------
# Jobs
# --------------------------------------------------------------
jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push image for other platforms
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          # Prevents the unknown/unknown arch
          # see https://github.com/docker/build-push-action/issues/820
          provenance: false
